### ISSUE TITLE
[FEAT]: organize cuda and wrappers - move functions to utils

### ISSUE THREAD

**Issue by LeonHibnik** [ingonyama-zk/icicle#179]
## Description

From review #172 - golang part reviewed, same applies to cuda and Rust
```[tasklist]
### Tasks
- [x] Move ReverseScalars from ntt to utils
- [x] Move VecScalarAdd from ntt
- [x] Move ToMontgomery from ntt to utils
```

**Comment by DmytroTym** [comment]
All completed in v1.0
