### ISSUE TITLE
[BUG]: new_curve_script missing params

### ISSUE THREAD

**Issue by LeonHibnik** [ingonyama-zk/icicle#186]
## Description

Script missing montgomery_r, montgomery_r_inv values for fq and fp structs, can't compile new curves

### FIx

```[tasklist]
### Tasks
- [ ] Add montgomery_r
- [ ] Add montgomery_r_inv
- [ ] Fix issue with arguments calling script
```

**Comment by krakhit** [comment]
In a specific use case, the BN254 curve uses a different root of unity, and the goal was to create a new icicle compile with these parameters for the same curve

The following tests were done
- [ ] Create a new json file bn254_new.json with updated parameters. The curve name in this file should still be "bn254" as the script generates use crate ark_bn254_new:: etc, run python3 ./curve_parameters/new_curve_script.py ./curve_parameters/bn254_zkwasm.json -new  which will create compilation errors. 
- [ ]  The other solution is to simply change the existing json file bn254.json with new parameters and use python3 ./curve_parameters/new_curve_script.py ./curve_parameters/bn254_zkwasm.json -update. This compiles and all tests pass. ![Screenshot 2023-09-18 at 13 48 27](https://github.com/ingonyama-zk/icicle/assets/61501745/dbc984a3-d9db-4794-a8dd-333290a5dfa5) All tests pass.
